"""remove_patient_id_unique_constraint

Revision ID: 585911eb82e2
Revises: f413176dafd4
Create Date: 2025-04-26 11:44:39.784426

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '585911eb82e2'
down_revision = 'f413176dafd4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop the index on patient_id
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add back the index on patient_id
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    # ### end Alembic commands ###