"""Add encryption to sensitive patient fields

Revision ID: f413176dafd4
Revises: 
Create Date: 2025-04-26 11:07:01.354936

"""
from alembic import op
import sqlalchemy as sa
from app.security.encryption import EncryptedString


# revision identifiers, used by Alembic.
revision = 'f413176dafd4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_specialists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('specialist_id', sa.String(), nullable=True),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('specialization', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_care_specialists_email'), 'care_specialists', ['email'], unique=True)
    op.create_index(op.f('ix_care_specialists_id'), 'care_specialists', ['id'], unique=False)
    op.create_index(op.f('ix_care_specialists_specialist_id'), 'care_specialists', ['specialist_id'], unique=True)
    op.create_table('patients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=True),
    sa.Column('first_name', EncryptedString(length=100), nullable=True),
    sa.Column('last_name', EncryptedString(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('gender', EncryptedString(length=10), nullable=True),
    sa.Column('diagnosis', EncryptedString(length=200), nullable=True),
    sa.Column('tumor_location', EncryptedString(length=100), nullable=True),
    sa.Column('tumor_stage', EncryptedString(length=50), nullable=True),
    sa.Column('treatment_plan', EncryptedString(length=1000), nullable=True),
    sa.Column('notes', EncryptedString(length=2000), nullable=True),
    sa.Column('care_specialist_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('treatment_cycle', sa.Integer(), nullable=True),
    sa.Column('biomarkers', EncryptedString(length=1000), nullable=True),
    sa.ForeignKeyConstraint(['care_specialist_id'], ['care_specialists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patients_id'), 'patients', ['id'], unique=False)
    op.create_index(op.f('ix_patients_patient_id'), 'patients', ['patient_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patients_patient_id'), table_name='patients')
    op.drop_index(op.f('ix_patients_id'), table_name='patients')
    op.drop_table('patients')
    op.drop_index(op.f('ix_care_specialists_specialist_id'), table_name='care_specialists')
    op.drop_index(op.f('ix_care_specialists_id'), table_name='care_specialists')
    op.drop_index(op.f('ix_care_specialists_email'), table_name='care_specialists')
    op.drop_table('care_specialists')
    # ### end Alembic commands ### 