"""Initial migration

Revision ID: 6bb95061cf71
Revises: 
Create Date: 2025-04-27 06:51:38.104040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb95061cf71'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_specialist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('diagnosis', sa.String(length=50), nullable=True),
    sa.Column('radius_mean', sa.Float(), nullable=True),
    sa.Column('texture_mean', sa.Float(), nullable=True),
    sa.Column('perimeter_mean', sa.Float(), nullable=True),
    sa.Column('area_mean', sa.Float(), nullable=True),
    sa.Column('smoothness_mean', sa.Float(), nullable=True),
    sa.Column('compactness_mean', sa.Float(), nullable=True),
    sa.Column('concavity_mean', sa.Float(), nullable=True),
    sa.Column('concave_points_mean', sa.Float(), nullable=True),
    sa.Column('symmetry_mean', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_mean', sa.Float(), nullable=True),
    sa.Column('radius_se', sa.Float(), nullable=True),
    sa.Column('texture_se', sa.Float(), nullable=True),
    sa.Column('perimeter_se', sa.Float(), nullable=True),
    sa.Column('area_se', sa.Float(), nullable=True),
    sa.Column('smoothness_se', sa.Float(), nullable=True),
    sa.Column('compactness_se', sa.Float(), nullable=True),
    sa.Column('concavity_se', sa.Float(), nullable=True),
    sa.Column('concave_points_se', sa.Float(), nullable=True),
    sa.Column('symmetry_se', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_se', sa.Float(), nullable=True),
    sa.Column('radius_worst', sa.Float(), nullable=True),
    sa.Column('texture_worst', sa.Float(), nullable=True),
    sa.Column('perimeter_worst', sa.Float(), nullable=True),
    sa.Column('area_worst', sa.Float(), nullable=True),
    sa.Column('smoothness_worst', sa.Float(), nullable=True),
    sa.Column('compactness_worst', sa.Float(), nullable=True),
    sa.Column('concavity_worst', sa.Float(), nullable=True),
    sa.Column('concave_points_worst', sa.Float(), nullable=True),
    sa.Column('symmetry_worst', sa.Float(), nullable=True),
    sa.Column('fractal_dimension_worst', sa.Float(), nullable=True),
    sa.Column('care_specialist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['care_specialist_id'], ['care_specialist.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patient')
    op.drop_table('care_specialist')
    # ### end Alembic commands ###
